### ISSUE TITLE
AsyncKeyedLock

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [DontEatOreo/DougaBot#1]
You may be interested in my library [AsyncKeyedLock](https://github.com/MarkCiliaVincenti/AsyncKeyedLock) also available on [NuGet](https://www.nuget.org/packages/AsyncKeyedLock) because you're doing some similar stuff, and this could help you.

**Comment by 4evy** [comment]
Hey @MarkCiliaVincenti I just implemented a queue solution with your library in https://github.com/DontEatOreo/DougaBot/commit/006d551945e7f37833465080a13136c57bd7e3b8

If possible can you tell to me how can I remove items manually from the internal dictionary? 

Although I have one little problem.

The problem is that:
User 1 queues a video, message returns "video is in position 1."
User 2 queues a video, message returns "video is in position 2."
**BUT** Later User 3 comes when both videos are finished and queues a new video it will return a message that the video is in position 3 even though in reality it's in position 1.

How can I go about removing videos from the count after they're done?

Also just out of curiosity how did you find this Project 🤔

**Comment by MarkCiliaVincenti** [comment]
You shouldn't manually delete. You're using the library wrong. You're doing GetOrAdd and then LockAsync. You only need the latter. GetOrAdd is used if you're going to be disposing the object yourself. You really only need to use LockAsync.
